services:
  steam-recommender:
    image: lquincarter/steam-game-recommender:latest
    ports:
      - "3030:80"
      - "3001:3001" # internal api
    restart: unless-stopped
    container_name: steam-game-recommender
    volumes:
      - ./data:/data
